<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="home.aspx.cs" Inherits="cs2313huangtao_test1.test4.home" %>


<asp:Content ID="Content1" runat="server" contentplaceholderid="ContentPlaceHolder1">
    <table class="auto-style1">
        <tr>
            <td>
                <h2 class="rs-cards-shelf-mainheader" style="margin: 0px; padding: 0px; color: rgb(29, 29, 31); font-weight: 600; quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; display: inline; font-family: &quot;SF Pro SC&quot;, &quot;SF Pro Display&quot;, &quot;SF Pro Icons&quot;, &quot;PingFang SC&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 28px; letter-spacing: 0.007em; line-height: 1.25; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(245, 245, 247); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">上新了，</h2>
                <span class="rs-cards-shelf-secondaryheader" style="margin-top: 22.4px; quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; display: inline; font-family: &quot;SF Pro SC&quot;, &quot;SF Pro Display&quot;, &quot;SF Pro Icons&quot;, &quot;PingFang SC&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 28px; font-weight: 600; letter-spacing: 0.007em; line-height: 1.25; color: rgb(110, 110, 115); font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(245, 245, 247); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">快来认识一下这些新朋友。</span>&nbsp;</td>
            <td style="width: 17px">&nbsp;</td>
        </tr>
        <tr>
            <td>
                <div data-core-scroller-item="" role="listitem" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; display: inline-block; scroll-snap-align: start; color: rgb(29, 29, 31); font-family: &quot;SF Pro SC&quot;, &quot;SF Pro Text&quot;, &quot;SF Pro Icons&quot;, &quot;PingFang SC&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 17px; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: nowrap; background-color: rgb(245, 245, 247); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                    <div class="rf-cards-scroller-itemview" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; display: flex; height: 29.4118rem; margin-inline: 0px 20px; transform: translateX(140px);">
                        <div class="rf-ccard rf-ccard-40 dd-color-apple-intelligence-lightblue" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal;">
                            <div class="as-util-relatedlink" data-trigger-click="click [data-relatedlink=':ri:_link']" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; cursor: pointer;">
                                <div class="rf-ccard-content rf-ccard-content-withfullimg" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; background-color: rgb(255, 255, 255); border-radius: 18px; box-shadow: rgba(0, 0, 0, 0.08) 2px 4px 12px; display: flex; flex-direction: row; height: 29.4118rem; overflow: hidden; position: relative; transition: 0.3s cubic-bezier(0, 0, 0.5, 1); white-space: normal; width: 23.5294rem; justify-content: center;">
                                    <div class="rf-ccard-img-full-wrapper" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; width: 400px;">
                                       <asp:ImageButton runat="server" alt="" class="rf-ccard-img-full" height="500" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; display: block; height: 500px; object-fit: cover; width: 400px;" width="400" ImageUrl="~/KSimage/homemac.jpg" OnClick="Unnamed1_Click1" /></div>
                                    <div class="rf-ccard-content-info" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; padding: 1.76471rem; width: 20rem; inset-inline-start: 0px; position: absolute;">
                                        <div class="rf-ccard-content-header" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; color: rgb(29, 29, 31); font-family: &quot;SF Pro SC&quot;, &quot;SF Pro Display&quot;, &quot;SF Pro Icons&quot;, &quot;PingFang SC&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 28px; font-weight: 600; letter-spacing: 0.007em; line-height: 1.25; margin-top: 0px; padding-top: 24px;">
                                            <a class="rf-ccard-content-headerlink" data-display-name="AOS: " data-index="1" data-relatedlink=":ri:_link" data-slot-name="Shelf-1" data-trigger-stoppropagation="true" href="home_categoty.aspx" style="color: rgb(29, 29, 31); letter-spacing: inherit; quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; display: inline-block; text-decoration: none;">hMacBook Air</a></div>
                                        <div class="rf-ccard-content-desc" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; color: rgb(29, 29, 31); font-family: &quot;SF Pro SC&quot;, &quot;SF Pro Text&quot;, &quot;SF Pro Icons&quot;, &quot;PingFang SC&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 17px; font-weight: 400; letter-spacing: 0px; line-height: 1.35296; margin-top: 0px; padding-top: 10px;">
                                            <span class="typography-body-tight rf-ccard-content-desccontent" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; font-family: &quot;SF Pro SC&quot;, &quot;SF Pro Text&quot;, &quot;SF Pro Icons&quot;, &quot;PingFang SC&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 17px; font-weight: 600; letter-spacing: 0px; line-height: 1.35296; display: block; padding-bottom: 6px;">身轻身手快。</span><span class="typography-body-reduced-tight rf-ccard-content-descprice" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; font-family: &quot;SF Pro SC&quot;, &quot;SF Pro Text&quot;, &quot;SF Pro Icons&quot;, &quot;PingFang SC&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: 400; letter-spacing: 0px; line-height: 1.35718;">RMB 333/月<span class="price-point-rate" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal;"><span>&nbsp;</span>(0% 费率 24 个月分期)<span>&nbsp;</span></span>起或<span>&nbsp;</span><b style="font-weight: 400; quotes: &quot;“&quot; &quot;”&quot;; font-style: normal;">RMB 
                                            7999</b><span>&nbsp;</span>起</span></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div data-core-scroller-item="" role="listitem" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; display: inline-block; scroll-snap-align: start; color: rgb(29, 29, 31); font-family: &quot;SF Pro SC&quot;, &quot;SF Pro Text&quot;, &quot;SF Pro Icons&quot;, &quot;PingFang SC&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 17px; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: nowrap; background-color: rgb(245, 245, 247); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                    <div class="rf-cards-scroller-itemview" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; display: flex; height: 29.4118rem; margin-inline-end: 20px; transform: translateX(140px);">
                        <div class="rf-ccard rf-ccard-40 dd-color-apple-intelligence-dark rf-ccard-darkbg" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal;">
                            <div class="as-util-relatedlink" data-trigger-click="click [data-relatedlink=':rj:_link']" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; cursor: pointer;">
                                <div class="rf-ccard-content rf-ccard-content-withfullimg" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; background-color: rgb(255, 255, 255); border-radius: 18px; box-shadow: rgba(0, 0, 0, 0.08) 2px 4px 12px; display: flex; flex-direction: row; height: 29.4118rem; overflow: hidden; position: relative; transition: 0.3s cubic-bezier(0, 0, 0.5, 1); white-space: normal; width: 23.5294rem; justify-content: center;">
                                    <div class="rf-ccard-img-full-wrapper" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; width: 400px;">
                                        <asp:ImageButton runat="server" alt="" class="rf-ccard-img-full" data-first-enter-image="true" height="500"  style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; display: block; height: 500px; object-fit: cover; width: 400px;" width="400" src="../KSimage/homehphone.jpg" OnClick="Unnamed2_Click" /></div>
                                    <div class="rf-ccard-content-info" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; padding: 1.76471rem; width: 20rem; inset-inline-start: 0px; position: absolute;">
                                        <div class="rf-ccard-content-header" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; color: rgb(255, 255, 255); font-family: &quot;SF Pro SC&quot;, &quot;SF Pro Display&quot;, &quot;SF Pro Icons&quot;, &quot;PingFang SC&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 28px; font-weight: 600; letter-spacing: 0.007em; line-height: 1.25; margin-top: 0px; padding-top: 24px;">
                                            <a class="rf-ccard-content-headerlink" data-display-name="AOS: " data-index="2" data-relatedlink=":rj:_link" data-slot-name="Shelf-1" data-trigger-stoppropagation="true"  style="color: rgb(255, 255, 255); letter-spacing: inherit; quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; display: inline-block; text-decoration: none;">iPhone 16&nbsp;Pro</a></div>
                                        <div class="rf-ccard-content-desc" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; color: rgb(255, 255, 255); font-family: &quot;SF Pro SC&quot;, &quot;SF Pro Text&quot;, &quot;SF Pro Icons&quot;, &quot;PingFang SC&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 17px; font-weight: 400; letter-spacing: 0px; line-height: 1.35296; margin-top: 0px; padding-top: 10px;">
                                            <span class="typography-body-tight rf-ccard-content-desccontent" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; font-family: &quot;SF Pro SC&quot;, &quot;SF Pro Text&quot;, &quot;SF Pro Icons&quot;, &quot;PingFang SC&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 17px; font-weight: 600; letter-spacing: 0px; line-height: 1.35296; display: block; padding-bottom: 6px;">iPhone 的巅峰之作</span><span class="typography-body-reduced-tight rf-ccard-content-descprice" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; font-family: &quot;SF Pro SC&quot;, &quot;SF Pro Text&quot;, &quot;SF Pro Icons&quot;, &quot;PingFang SC&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: 400; letter-spacing: 0px; line-height: 1.35718;">RMB 333/月<span class="price-point-rate" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal;"><span>&nbsp;</span>(0% 费率 24 个月分期)<span>&nbsp;</span></span>起或<span>&nbsp;</span><b style="font-weight: 400; quotes: &quot;“&quot; &quot;”&quot;; font-style: normal;">RMB 
                                            7999</b><span>&nbsp;</span>起</span></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>            
                <div data-core-scroller-item="" role="listitem" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; display: inline-block; scroll-snap-align: start; color: rgb(29, 29, 31); font-family: &quot;SF Pro SC&quot;, &quot;SF Pro Text&quot;, &quot;SF Pro Icons&quot;, &quot;PingFang SC&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 17px; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: nowrap; background-color: rgb(245, 245, 247); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                    <div class="rf-cards-scroller-itemview" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; display: flex; height: 29.4118rem; margin-inline-end: 20px; transform: translateX(140px);">
                        <div class="rf-ccard rf-ccard-40 dd-color-apple-intelligence" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal;">
                            <div class="as-util-relatedlink" data-trigger-click="click [data-relatedlink=':rl:_link']" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; cursor: pointer;">
                                <div class="rf-ccard-content rf-ccard-content-withfullimg" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; background-color: rgb(255, 255, 255); border-radius: 18px; box-shadow: rgba(0, 0, 0, 0.08) 2px 4px 12px; display: flex; flex-direction: row; height: 29.4118rem; overflow: hidden; position: relative; transition: 0.3s cubic-bezier(0, 0, 0.5, 1); white-space: normal; width: 23.5294rem; justify-content: center;">
                                    <div class="rf-ccard-img-full-wrapper" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; width: 400px;">
                                        <asp:ImageButton runat="server" alt="" class="rf-ccard-img-full" height="500" src="../KSimage/homehpadair.jpg" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; display: block; height: 500px; object-fit: cover; width: 400px;" width="400" OnClick="Unnamed3_Click" /></div>
                                    <div class="rf-ccard-content-info" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; padding: 1.76471rem; width: 20rem; inset-inline-start: 0px; position: absolute;">
                                        <div class="rf-ccard-content-header" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; color: rgb(29, 29, 31); font-family: &quot;SF Pro SC&quot;, &quot;SF Pro Display&quot;, &quot;SF Pro Icons&quot;, &quot;PingFang SC&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 28px; font-weight: 600; letter-spacing: 0.007em; line-height: 1.25; margin-top: 0px; padding-top: 24px;">
                                            <a class="rf-ccard-content-headerlink" data-display-name="AOS: " data-index="4" data-relatedlink=":rl:_link" data-slot-name="Shelf-1" data-trigger-stoppropagation="true"  style="color: rgb(29, 29, 31); letter-spacing: inherit; quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; display: inline-block; text-decoration: none;">iPad Air</a></div>
                                        <div class="rf-ccard-content-desc" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; color: rgb(29, 29, 31); font-family: &quot;SF Pro SC&quot;, &quot;SF Pro Text&quot;, &quot;SF Pro Icons&quot;, &quot;PingFang SC&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 17px; font-weight: 400; letter-spacing: 0px; line-height: 1.35296; margin-top: 0px; padding-top: 10px;">
                                            <span class="typography-body-tight rf-ccard-content-desccontent" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; font-family: &quot;SF Pro SC&quot;, &quot;SF Pro Text&quot;, &quot;SF Pro Icons&quot;, &quot;PingFang SC&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 17px; font-weight: 600; letter-spacing: 0px; line-height: 1.35296; display: block; padding-bottom: 6px;">快如飞</span><span class="typography-body-reduced-tight rf-ccard-content-descprice" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; font-family: &quot;SF Pro SC&quot;, &quot;SF Pro Text&quot;, &quot;SF Pro Icons&quot;, &quot;PingFang SC&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: 400; letter-spacing: 0px; line-height: 1.35718;">RMB 200/月<span class="price-point-rate" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal;"><span>&nbsp;</span>(0% 费率 24 个月分期)<span>&nbsp;</span></span>起或<span>&nbsp;</span><b style="font-weight: 400; quotes: &quot;“&quot; &quot;”&quot;; font-style: normal;">RMB 
                                            4799</b><span>&nbsp;</span>起</span></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div data-core-scroller-item="" role="listitem" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; display: inline-block; scroll-snap-align: start; color: rgb(29, 29, 31); font-family: &quot;SF Pro SC&quot;, &quot;SF Pro Text&quot;, &quot;SF Pro Icons&quot;, &quot;PingFang SC&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 17px; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: nowrap; background-color: rgb(245, 245, 247); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                    <div class="rf-cards-scroller-itemview" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; display: flex; height: 29.4118rem; margin-inline-end: 20px; transform: translateX(140px);">
                        <div class="rf-ccard rf-ccard-40" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal;">
                            <div class="as-util-relatedlink" data-trigger-click="click [data-relatedlink=':rm:_link']" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; cursor: pointer;">
                                <div class="rf-ccard-content rf-ccard-content-withfullimg" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; background-color: rgb(255, 255, 255); border-radius: 18px; box-shadow: rgba(0, 0, 0, 0.08) 2px 4px 12px; display: flex; flex-direction: row; height: 29.4118rem; overflow: hidden; position: relative; transition: 0.3s cubic-bezier(0, 0, 0.5, 1); white-space: normal; width: 23.5294rem; justify-content: center;">
                                    <div class="rf-ccard-img-full-wrapper" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; width: 400px;">
                                        <asp:ImageButton runat="server" alt="" class="rf-ccard-img-full" height="500" src="../KSimage/watch-s10.jpg" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; display: block; height: 500px; object-fit: cover; width: 400px;" width="400" OnClick="Unnamed4_Click" /></div>
                                    <div class="rf-ccard-content-info" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; padding: 1.76471rem; width: 20rem; inset-inline-start: 0px; position: absolute;">
                                        <div class="rf-ccard-content-header" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; color: rgb(29, 29, 31); font-family: &quot;SF Pro SC&quot;, &quot;SF Pro Display&quot;, &quot;SF Pro Icons&quot;, &quot;PingFang SC&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 28px; font-weight: 600; letter-spacing: 0.007em; line-height: 1.25; margin-top: 0px; padding-top: 24px;">
                                            <a class="rf-ccard-content-headerlink" data-display-name="AOS: " data-index="5" data-relatedlink=":rm:_link" data-slot-name="Shelf-1" data-trigger-stoppropagation="true"  style="color: rgb(29, 29, 31); letter-spacing: inherit; quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; display: inline-block; text-decoration: none;">Apple&nbsp;Watch Series&nbsp;10</a></div>
                                        <div class="rf-ccard-content-desc" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; color: rgb(29, 29, 31); font-family: &quot;SF Pro SC&quot;, &quot;SF Pro Text&quot;, &quot;SF Pro Icons&quot;, &quot;PingFang SC&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 17px; font-weight: 400; letter-spacing: 0px; line-height: 1.35296; margin-top: 0px; padding-top: 10px;">
                                            <span class="typography-body-tight rf-ccard-content-desccontent" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; font-family: &quot;SF Pro SC&quot;, &quot;SF Pro Text&quot;, &quot;SF Pro Icons&quot;, &quot;PingFang SC&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 17px; font-weight: 600; letter-spacing: 0px; line-height: 1.35296; display: block; padding-bottom: 6px;">薄爆表</span><span class="typography-body-reduced-tight rf-ccard-content-descprice" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; font-family: &quot;SF Pro SC&quot;, &quot;SF Pro Text&quot;, &quot;SF Pro Icons&quot;, &quot;PingFang SC&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: 400; letter-spacing: 0px; line-height: 1.35718;"><b style="font-weight: 400; quotes: &quot;“&quot; &quot;”&quot;; font-style: normal;">RMB 2999</b><span>&nbsp;</span>起</span></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div data-core-scroller-item="" role="listitem" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; display: inline-block; scroll-snap-align: start; color: rgb(29, 29, 31); font-family: &quot;SF Pro SC&quot;, &quot;SF Pro Text&quot;, &quot;SF Pro Icons&quot;, &quot;PingFang SC&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 17px; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: nowrap; background-color: rgb(245, 245, 247); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                    <div class="rf-cards-scroller-itemview" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; display: flex; height: 29.4118rem; margin-inline-end: 20px; transform: translateX(140px);">
                        <div class="rf-ccard rf-ccard-40" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal;">
                            <div class="as-util-relatedlink" data-trigger-click="click [data-relatedlink=':rn:_link']" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; cursor: pointer;">
                                <div class="rf-ccard-content rf-ccard-content-withfullimg" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; background-color: rgb(255, 255, 255); border-radius: 18px; box-shadow: rgba(0, 0, 0, 0.08) 2px 4px 12px; display: flex; flex-direction: row; height: 29.4118rem; overflow: hidden; position: relative; transition: 0.3s cubic-bezier(0, 0, 0.5, 1); white-space: normal; width: 23.5294rem; justify-content: center;">
                                    <div class="rf-ccard-img-full-wrapper" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; width: 400px;">
                                        <asp:ImageButton runat="server" alt="" class="rf-ccard-img-full" height="500" src="../KSimage/watch-pride.png" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; display: block; height: 500px; object-fit: cover; width: 400px;" width="400" OnClick="Unnamed5_Click" /></div>
                                    <div class="rf-ccard-content-info" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; padding: 1.76471rem; width: 20rem; inset-inline-start: 0px; position: absolute;">
                                        <div class="rf-ccard-content-header" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; color: rgb(29, 29, 31); font-family: &quot;SF Pro SC&quot;, &quot;SF Pro Display&quot;, &quot;SF Pro Icons&quot;, &quot;PingFang SC&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 28px; font-weight: 600; letter-spacing: 0.007em; line-height: 1.25; margin-top: 0px; padding-top: 24px;">
                                            <a class="rf-ccard-content-headerlink" data-display-name="AOS: " data-index="6" data-relatedlink=":rn:_link" data-slot-name="Shelf-1" data-trigger-stoppropagation="true"  style="color: rgb(29, 29, 31); letter-spacing: inherit; quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; display: inline-block; text-decoration: none;">
                                            <div class="dd-compact-right-large-25 dd-compact-right-small-25" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; margin-inline-end: 85px;">
                                                Apple&nbsp;Watch 彩虹版运动型表带</div>
                                            </a>
                                        </div>
                                        <div class="rf-ccard-content-desc" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; color: rgb(29, 29, 31); font-family: &quot;SF Pro SC&quot;, &quot;SF Pro Text&quot;, &quot;SF Pro Icons&quot;, &quot;PingFang SC&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 17px; font-weight: 400; letter-spacing: 0px; line-height: 1.35296; margin-top: 0px; padding-top: 10px;">
                                            <span class="typography-body-tight rf-ccard-content-desccontent" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; font-family: &quot;SF Pro SC&quot;, &quot;SF Pro Text&quot;, &quot;SF Pro Icons&quot;, &quot;PingFang SC&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 17px; font-weight: 600; letter-spacing: 0px; line-height: 1.35296; display: block; padding-bottom: 6px;">尽情多彩</span><span class="typography-body-reduced-tight rf-ccard-content-descprice" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; font-family: &quot;SF Pro SC&quot;, &quot;SF Pro Text&quot;, &quot;SF Pro Icons&quot;, &quot;PingFang SC&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: 400; letter-spacing: 0px; line-height: 1.35718;">RMB 379</span></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div data-core-scroller-item="" role="listitem" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; display: inline-block; scroll-snap-align: start; color: rgb(29, 29, 31); font-family: &quot;SF Pro SC&quot;, &quot;SF Pro Text&quot;, &quot;SF Pro Icons&quot;, &quot;PingFang SC&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 17px; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: nowrap; background-color: rgb(245, 245, 247); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                    <div class="rf-cards-scroller-itemview" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; display: flex; height: 29.4118rem; margin-inline-end: 20px; transform: translateX(140px);">
                        <div class="rf-ccard rf-ccard-40 dd-color-apple-intelligence dd-card-eyebrow-100 " style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal;">
                            <div class="as-util-relatedlink" data-trigger-click="click [data-relatedlink=':ro:_link']" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; cursor: pointer;">
                                <div class="rf-ccard-content rf-ccard-content-withfullimg" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; background-color: rgb(255, 255, 255); border-radius: 18px; box-shadow: rgba(0, 0, 0, 0.08) 2px 4px 12px; display: flex; flex-direction: row; height: 29.4118rem; overflow: hidden; position: relative; transition: 0.3s cubic-bezier(0, 0, 0.5, 1); white-space: normal; width: 23.5294rem; justify-content: center;">
                                    <div class="rf-ccard-img-full-wrapper" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; width: 400px;">
                                        <asp:ImageButton runat="server" alt="" class="rf-ccard-img-full" height="500" src="../KSimage/hphone-16e.jpg" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; display: block; height: 500px; object-fit: cover; width: 400px;" width="400" OnClick="Unnamed1_Click" /></div>
                                    <div class="rf-ccard-content-info" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; padding: 1.76471rem; width: 20rem; inset-inline-start: 0px; position: absolute;">
                                        <div class="rf-ccard-content-header" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; color: rgb(29, 29, 31); font-family: &quot;SF Pro SC&quot;, &quot;SF Pro Display&quot;, &quot;SF Pro Icons&quot;, &quot;PingFang SC&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 28px; font-weight: 600; letter-spacing: 0.007em; line-height: 1.25; margin-top: 0px; padding-top: 24px;">
                                            <a class="rf-ccard-content-headerlink" data-display-name="AOS: " data-index="7" data-relatedlink=":ro:_link" data-slot-name="Shelf-1" data-trigger-stoppropagation="true"  style="color: rgb(29, 29, 31); letter-spacing: inherit; quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; display: inline-block; text-decoration: none;">iPhone&nbsp;16e</a></div>
                                        <div class="rf-ccard-content-desc" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; color: rgb(29, 29, 31); font-family: &quot;SF Pro SC&quot;, &quot;SF Pro Text&quot;, &quot;SF Pro Icons&quot;, &quot;PingFang SC&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 17px; font-weight: 400; letter-spacing: 0px; line-height: 1.35296; margin-top: 0px; padding-top: 10px;">
                                            <span class="typography-body-tight rf-ccard-content-desccontent" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; font-family: &quot;SF Pro SC&quot;, &quot;SF Pro Text&quot;, &quot;SF Pro Icons&quot;, &quot;PingFang SC&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 17px; font-weight: 600; letter-spacing: 0px; line-height: 1.35296; display: block; padding-bottom: 6px;">iPhone 上新，超值刷新。</span><span class="typography-body-reduced-tight rf-ccard-content-descprice" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; font-family: &quot;SF Pro SC&quot;, &quot;SF Pro Text&quot;, &quot;SF Pro Icons&quot;, &quot;PingFang SC&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: 400; letter-spacing: 0px; line-height: 1.35718;">RMB 187/月<span class="price-point-rate" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal;"><span>&nbsp;</span>(0% 费率 24 个月分期)<span>&nbsp;</span></span>起或<span>&nbsp;</span><b style="font-weight: 400; quotes: &quot;“&quot; &quot;”&quot;; font-style: normal;">RMB 
                                            4499</b><span>&nbsp;</span>起</span></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div data-core-scroller-item="" role="listitem" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; display: inline-block; scroll-snap-align: start; color: rgb(29, 29, 31); font-family: &quot;SF Pro SC&quot;, &quot;SF Pro Text&quot;, &quot;SF Pro Icons&quot;, &quot;PingFang SC&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 17px; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: nowrap; background-color: rgb(245, 245, 247); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                    <div class="rf-cards-scroller-itemview" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; display: flex; height: 29.4118rem; margin-inline-end: 20px; transform: translateX(140px);">
                        <div class="rf-ccard rf-ccard-40" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal;">
                            <div class="as-util-relatedlink" data-trigger-click="click [data-relatedlink=':rp:_link']" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; cursor: pointer;">
                                <div class="rf-ccard-content rf-ccard-content-withfullimg" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; background-color: rgb(255, 255, 255); border-radius: 18px; box-shadow: rgba(0, 0, 0, 0.08) 2px 4px 12px; display: flex; flex-direction: row; height: 29.4118rem; overflow: hidden; position: relative; transition: 0.3s cubic-bezier(0, 0, 0.5, 1); white-space: normal; width: 23.5294rem; justify-content: center;">
                                    <div class="rf-ccard-img-full-wrapper" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; width: 400px;">
                                        <asp:ImageButton runat="server" alt="" class="rf-ccard-img-full" height="500" src="../KSimage/hpad.jpg" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; display: block; height: 500px; object-fit: cover; width: 400px;" width="400" OnClick="Unnamed7_Click" /></div>
                                    <div class="rf-ccard-content-info" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; padding: 1.76471rem; width: 20rem; inset-inline-start: 0px; position: absolute;">
                                        <div class="rf-ccard-content-header" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; color: rgb(29, 29, 31); font-family: &quot;SF Pro SC&quot;, &quot;SF Pro Display&quot;, &quot;SF Pro Icons&quot;, &quot;PingFang SC&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 28px; font-weight: 600; letter-spacing: 0.007em; line-height: 1.25; margin-top: 0px; padding-top: 24px;">
                                            <a class="rf-ccard-content-headerlink" data-display-name="AOS: " data-index="8" data-relatedlink=":rp:_link" data-slot-name="Shelf-1" data-trigger-stoppropagation="true"  style="color: rgb(29, 29, 31); letter-spacing: inherit; quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; display: inline-block; text-decoration: none;">iPad</a></div>
                                        <div class="rf-ccard-content-desc" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; color: rgb(29, 29, 31); font-family: &quot;SF Pro SC&quot;, &quot;SF Pro Text&quot;, &quot;SF Pro Icons&quot;, &quot;PingFang SC&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 17px; font-weight: 400; letter-spacing: 0px; line-height: 1.35296; margin-top: 0px; padding-top: 10px;">
                                            <span class="typography-body-tight rf-ccard-content-desccontent" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; font-family: &quot;SF Pro SC&quot;, &quot;SF Pro Text&quot;, &quot;SF Pro Icons&quot;, &quot;PingFang SC&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 17px; font-weight: 600; letter-spacing: 0px; line-height: 1.35296; display: block; padding-bottom: 6px;">可圈可点可画心</span><span class="typography-body-reduced-tight rf-ccard-content-descprice" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; font-family: &quot;SF Pro SC&quot;, &quot;SF Pro Text&quot;, &quot;SF Pro Icons&quot;, &quot;PingFang SC&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: 400; letter-spacing: 0px; line-height: 1.35718;">RMB 125/月<span class="price-point-rate" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal;"><span>&nbsp;</span>(0% 费率 24 个月分期)<span>&nbsp;</span></span>起或<span>&nbsp;</span><b style="font-weight: 400; quotes: &quot;“&quot; &quot;”&quot;; font-style: normal;">RMB 
                                            2999</b><span>&nbsp;</span>起</span></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div data-core-scroller-item="" role="listitem" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; display: inline-block; scroll-snap-align: start; color: rgb(29, 29, 31); font-family: &quot;SF Pro SC&quot;, &quot;SF Pro Text&quot;, &quot;SF Pro Icons&quot;, &quot;PingFang SC&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 17px; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: nowrap; background-color: rgb(245, 245, 247); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                    <div class="rf-cards-scroller-itemview" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; display: flex; height: 29.4118rem; margin-inline-end: 20px; transform: translateX(140px);">
                        <div class="rf-ccard rf-ccard-40 dd-color-apple-intelligence" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal;">
                            <div class="as-util-relatedlink" data-trigger-click="click [data-relatedlink=':rq:_link']" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; cursor: pointer;">
                                <div class="rf-ccard-content rf-ccard-content-withfullimg" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; background-color: rgb(255, 255, 255); border-radius: 18px; box-shadow: rgba(0, 0, 0, 0.08) 2px 4px 12px; display: flex; flex-direction: row; height: 29.4118rem; overflow: hidden; position: relative; transition: 0.3s cubic-bezier(0, 0, 0.5, 1); white-space: normal; width: 23.5294rem; justify-content: center;">
                                    <div class="rf-ccard-img-full-wrapper" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; width: 400px;">
                                        <asp:ImageButton runat="server" alt="" class="rf-ccard-img-full" height="500" src="../KSimage/hmac-studio.jpg" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; display: block; height: 500px; object-fit: cover; width: 400px;" width="400" OnClick="Unnamed8_Click" /></div>
                                    <div class="rf-ccard-content-info" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; padding: 1.76471rem; width: 20rem; inset-inline-start: 0px; position: absolute;">
                                        <div class="rf-ccard-content-header" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; color: rgb(29, 29, 31); font-family: &quot;SF Pro SC&quot;, &quot;SF Pro Display&quot;, &quot;SF Pro Icons&quot;, &quot;PingFang SC&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 28px; font-weight: 600; letter-spacing: 0.007em; line-height: 1.25; margin-top: 0px; padding-top: 24px;">
                                            <a class="rf-ccard-content-headerlink" data-display-name="AOS: " data-index="9" data-relatedlink=":rq:_link" data-slot-name="Shelf-1" data-trigger-stoppropagation="true"  style="color: rgb(29, 29, 31); letter-spacing: inherit; quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; display: inline-block; text-decoration: none;">Mac Studio</a></div>
                                        <div class="rf-ccard-content-desc" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; color: rgb(29, 29, 31); font-family: &quot;SF Pro SC&quot;, &quot;SF Pro Text&quot;, &quot;SF Pro Icons&quot;, &quot;PingFang SC&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 17px; font-weight: 400; letter-spacing: 0px; line-height: 1.35296; margin-top: 0px; padding-top: 10px;">
                                            <span class="typography-body-tight rf-ccard-content-desccontent" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; font-family: &quot;SF Pro SC&quot;, &quot;SF Pro Text&quot;, &quot;SF Pro Icons&quot;, &quot;PingFang SC&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 17px; font-weight: 600; letter-spacing: 0px; line-height: 1.35296; display: block; padding-bottom: 6px;">硬核加载</span><span class="typography-body-reduced-tight rf-ccard-content-descprice" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; font-family: &quot;SF Pro SC&quot;, &quot;SF Pro Text&quot;, &quot;SF Pro Icons&quot;, &quot;PingFang SC&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: 400; letter-spacing: 0px; line-height: 1.35718;">RMB 687/月<span class="price-point-rate" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal;"><span>&nbsp;</span>(0% 费率 24 个月分期)<span>&nbsp;</span></span>起或<span>&nbsp;</span><b style="font-weight: 400; quotes: &quot;“&quot; &quot;”&quot;; font-style: normal;">RMB 
                                            16,499</b><span>&nbsp;</span>起</span></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>              
                <div data-core-scroller-item="" role="listitem" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; display: inline-block; scroll-snap-align: start; color: rgb(29, 29, 31); font-family: &quot;SF Pro SC&quot;, &quot;SF Pro Text&quot;, &quot;SF Pro Icons&quot;, &quot;PingFang SC&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 17px; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: nowrap; background-color: rgb(245, 245, 247); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                    <div class="rf-cards-scroller-itemview" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; display: flex; height: 29.4118rem; margin-inline-end: 20px; transform: translateX(140px);">
                        <div class="rf-ccard rf-ccard-40 rf-ccard-darkbg" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal;">
                            <div class="as-util-relatedlink" data-trigger-click="click [data-relatedlink=':rs:_link']" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; cursor: pointer;">
                                <div class="rf-ccard-content rf-ccard-content-withfullimg" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; background-color: rgb(255, 255, 255); border-radius: 18px; box-shadow: rgba(0, 0, 0, 0.08) 2px 4px 12px; display: flex; flex-direction: row; height: 29.4118rem; overflow: hidden; position: relative; transition: 0.3s cubic-bezier(0, 0, 0.5, 1); white-space: normal; width: 23.5294rem; justify-content: center;">
                                    <div class="rf-ccard-img-full-wrapper" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; width: 400px;">
                                        <asp:ImageButton runat="server" alt="" class="rf-ccard-img-full" height="500" src="../KSimage/hwatch-ultra.jpg" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; display: block; height: 500px; object-fit: cover; width: 400px;" width="400" OnClick="Unnamed9_Click" /></div>
                                    <div class="rf-ccard-content-info" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; padding: 1.76471rem; width: 20rem; inset-inline-start: 0px; position: absolute;">
                                        <div class="rf-ccard-content-header" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; color: rgb(255, 255, 255); font-family: &quot;SF Pro SC&quot;, &quot;SF Pro Display&quot;, &quot;SF Pro Icons&quot;, &quot;PingFang SC&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 28px; font-weight: 600; letter-spacing: 0.007em; line-height: 1.25; margin-top: 0px; padding-top: 24px;">
                                            <a class="rf-ccard-content-headerlink" data-display-name="AOS: " data-index="11" data-relatedlink=":rs:_link" data-slot-name="Shelf-1" data-trigger-stoppropagation="true"  style="color: rgb(255, 255, 255); letter-spacing: inherit; quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; display: inline-block; text-decoration: none;">Apple Watch Ultra&nbsp;2</a></div>
                                        <div class="rf-ccard-content-desc" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; color: rgb(255, 255, 255); font-family: &quot;SF Pro SC&quot;, &quot;SF Pro Text&quot;, &quot;SF Pro Icons&quot;, &quot;PingFang SC&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 17px; font-weight: 400; letter-spacing: 0px; line-height: 1.35296; margin-top: 0px; padding-top: 10px;">
                                            <span class="typography-body-tight rf-ccard-content-desccontent" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; font-family: &quot;SF Pro SC&quot;, &quot;SF Pro Text&quot;, &quot;SF Pro Icons&quot;, &quot;PingFang SC&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 17px; font-weight: 600; letter-spacing: 0px; line-height: 1.35296; display: block; padding-bottom: 6px;">野出新一面</span><span class="typography-body-reduced-tight rf-ccard-content-descprice" style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal; font-family: &quot;SF Pro SC&quot;, &quot;SF Pro Text&quot;, &quot;SF Pro Icons&quot;, &quot;PingFang SC&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: 400; letter-spacing: 0px; line-height: 1.35718;"><span style="quotes: &quot;“&quot; &quot;”&quot;; font-style: normal;">RMB 6499</span><span>&nbsp;</span>起</span></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>             
            </td>
            <td style="width: 17px">&nbsp;</td>
        </tr>
    </table>
</asp:Content>



